[[server]]
# Listening / Socket settings
listen = "0.0.0.0:80"
listen_ssl = "0.0.0.0:443"

# HTTP settings
server_name = "localhost"

# SSL settings
ssl_certificate = "../certs/default.cert"
ssl_certificate_key = "../certs/default.key"

# Proxy to server
[[server.location]]
path = "/api"
proxy_to = "http://127.0.0.1:8080"
ip_forward = true
host_forward = true
trust_proxy = true

# Static file server
[[server.location]]
path = "/assets"
root = "c:/var/www/html"
index = "index.html"
fallback = "404.html"

# Redirect all to index.html (Perfect for SPAs)
[[server.location]]
path = "/"
root = "c:/var/www/html"
rewrite = "index.html"